name: Deploy to GitHub Packages

on:
  push:
    tags:
      - 'release-v*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Asia/Hong_Kong'

      - name: Install dependencies
        run: npm install

      - name: Run lint check
        run: npm run lint
        if: success()
        continue-on-error: true # Allow soft failure if lint script is missing

      # - name: Run tests
      #   run: npm test //todo

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: release

    needs: validate
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dev-force'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Pack package
        run: npm pack

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.
            - Package: @dev-force/nestjs-data-generic@${{ github.ref_name }}
            - Published to GitHub Packages
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dev-force-nestjs-data-generic-${{ github.ref_name }}.tgz
          asset_name: nestjs-data-generic-${{ github.ref_name }}.tgz
          asset_content_type: application/tgz
